\context ChordNames
	\chords {
		\set chordChanges = ##t
		% intro
		R1*3  |

		% santo...
		a4. e8 ~ e2  |
%% 5
		cis4.:m b8 ~ b2  |
		fis2:m7 e:/gis  |
		a2. b4  |
		a4. e8 ~ e2  |
		cis4.:m b8 ~ b2  |
%% 10
		fis2:m7 e:/gis  |
		a2. fis4:m/b  |
		e1  |

		% osanna...
		a2 b2:/a  |
		a2 b2:/a  |
%% 15
		fis1:m7  |
		a2:/b a  |

		% santo...
		a4. e8 ~ e2  |
		cis4.:m b8 ~ b2  |
		fis2:m7 e:/gis  |
%% 20
		a2. b4  |
		a4. e8 ~ e2  |
		cis4.:m b8 ~ b2  |
		fis2:m7 e:/gis  |
		a2. fis4:m/b  |
%% 25
		e1  |

		% benedetto...
		b1  |
		a1  |
		e1  |
		b1  |
%% 30
		% osanna...
		a2 b2:/a  |
		a2 b2:/a  |
		fis1:m7  |
		a2:/b a  |
		a4. e8 ~ e2  |
%% 35
		cis4.:m b8 ~ b2  |
		a2 a:/b  |
		e1  |
	}
